language: cpp
dist: trusty
sudo: false


compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9
    - COMPILER=g++-5 CCOMPILER=gcc-5

#matrix:
#  allow_failures:
#    - env: COMPILER=g++-4.6 CCOMPILER=gcc-4.6


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake
    packages:
      - g++-4.9
      - g++-5
      - cmake
      - cmake-data

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build && cd build
  - cmake -LAH -DTESTING=ON ..

script:
 - make
 - ./runtests

